-- Supabase Schema for IncubX

-- 1. Users table (Extends Supabase Auth)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  full_name TEXT,
  phone TEXT,
  bio TEXT,
  linkedin_url TEXT,
  github_url TEXT,
  twitter_url TEXT,
  avatar_url TEXT,
  role TEXT,
  disc_results JSONB,
  profile_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policies for users
CREATE POLICY "Users can view their own profile" 
  ON public.users FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
  ON public.users FOR UPDATE 
  USING (auth.uid() = id);

-- 2. Registration Tokens table
CREATE TABLE IF NOT EXISTS public.registration_tokens (
  token TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  role TEXT NOT NULL,
  org_name TEXT,
  expires_at TIMESTAMPTZ,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.registration_tokens ENABLE ROW LEVEL SECURITY;

-- Policies for registration_tokens (Public read for validation)
CREATE POLICY "Public read access for token validation" 
  ON public.registration_tokens FOR SELECT 
  USING (TRUE);

-- 3. DISC Results table (Secondary storage)
CREATE TABLE IF NOT EXISTS public.disc_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
  scores JSONB NOT NULL,
  primary_type TEXT NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.disc_results ENABLE ROW LEVEL SECURITY;

-- Policies for disc_results
CREATE POLICY "Users can view their own DISC results" 
  ON public.disc_results FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own DISC results" 
  ON public.disc_results FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- 4. Storage Bucket for Avatars
-- Note: This part might need to be done via Supabase Dashboard or API, 
-- but we can declare the policy if the bucket is created.
-- INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true);

-- Storage Policies
-- CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
-- CREATE POLICY "Upload own avatar" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

-- Function to handle user creation on auth signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, full_name, role)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''), 
    COALESCE(NEW.raw_user_meta_data->>'role', 'member')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create user profile on signup
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
